const C=window.CAREERAXIS_CONFIG||{};let data={jobs:[],resources:[],events:[],videos:[],careerPaths:[]};let lang='en';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function load(){try{data=await (await fetch('data/content.json')).json()}catch(e){} render(); bindSocial();}
function bindSocial(){document.querySelectorAll('[data-social]').forEach(a=>{const k=a.dataset.social;a.href=(C.social&&C.social[k])||'#';if(a.href==='#')a.style.opacity='.45'})}
function render(){
  const params = new URLSearchParams(location.search);
  const r = params.get('admin') === 'secure'
    ? 'admin'
    : (location.hash.slice(1) || 'home');if(r===C.adminRoute||r==='admin')return admin();const pages={home:home,jobs:jobs,youtube:youtube,resources:resources,careers:careers,calendar:calendar,community:community};(pages[r]||home)();window.scrollTo({top:0,behavior:'smooth'});bindSocial()}
function home(){const featured=data.jobs.filter(x=>x.featured).slice(0,3), vids=data.videos.slice(0,3), res=data.resources.slice(0,4);$('#app').innerHTML=`<section class="hero"><div class="hero-inner"><div><div class="tag">FREE CAREER & JOB INFORMATION</div><h1>Knowledge <span class="gold">to Success.</span></h1><p>Jobs, career guidance, education updates, preparation resources and practical YouTube job information — organized in one place.</p><div class="actions"><a class="btn primary" href="#jobs">Explore Latest Jobs</a><a class="btn secondary" href="#youtube">Watch Latest Videos</a></div></div><div class="hero-card"><img src="assets/careeraxis-logo.png" alt="CareerAxis Academy logo"><p style="text-align:center;margin:14px 0 0">CareerAxis Academy</p></div></div></section><section class="section"><div class="section-head"><div><h2>Latest Job Updates</h2><p class="muted">Fresh opportunities, eligibility and official application links.</p></div><a class="btn" href="#jobs" style="border:1px solid var(--line)">View all jobs</a></div><div class="grid">${featured.length?featured.map(jobCard).join(''):`<div class="empty" style="grid-column:1/-1">Jobs will appear here after you add them in the Admin Dashboard.</div>`}</div></section><section class="section" style="padding-top:10px"><div class="section-head"><div><h2>🎥 Latest from YouTube</h2><p class="muted">Job updates and career guidance from CareerAxis Academy.</p></div><a class="btn" href="#youtube" style="border:1px solid var(--line)">See all videos</a></div><div class="grid">${vids.length?vids.map(videoCard).join(''):`<div class="empty" style="grid-column:1/-1">Connect your YouTube Channel ID in Admin → Integrations to automatically populate videos.</div>`}</div></section><section class="section community"><div class="section-head"><div><h2>Join CareerAxis Academy Community</h2><p class="muted">Stay updated across your favorite platforms.</p></div></div><div class="socials">${socialCard('YouTube','Subscribe for job and career updates','youtube','▶')} ${socialCard('Telegram','Join the latest update channel','telegram','✈')} ${socialCard('WhatsApp','Join the community','whatsapp','◉')} ${socialCard('Instagram','Follow CareerAxis Academy','instagram','◎')}</div></section><section class="section"><div class="section-head"><div><h2>Latest Resources</h2><p class="muted">Drive-powered preparation materials and previous papers.</p></div><a class="btn" href="#resources" style="border:1px solid var(--line)">Browse resources</a></div><div class="grid">${res.length?res.map(resourceCard).join(''):`<div class="empty" style="grid-column:1/-1">Map Google Drive folders in Admin → Google Drive to show resources automatically.</div>`}</div></section>`}
function jobCard(j){return `<article class="card"><span class="tag">${esc(j.category||'Job')}</span><div class="job-title">${esc(j.title)}</div><b>${esc(j.company)}</b><p class="muted">${esc(j.location||'India')} · ${esc(j.qualification||'Eligibility on official page')}</p><p><b>Last date:</b> ${esc(j.lastDate||'Check official notice')}</p><a class="btn primary" href="${esc(j.applyUrl||'#')}" target="_blank" rel="noopener">Apply Now</a></article>`}
function videoCard(v){return `<article class="card video-card"><div class="thumb">▶</div><div class="body"><span class="tag">YouTube</span><div class="job-title">${esc(v.title)}</div><p class="muted">${esc(v.publishedAt||'Latest update')}</p><a class="btn primary" href="${esc(v.url||'#')}" target="_blank" rel="noopener">Watch Now</a></div></article>`}
function resourceCard(r){return `<article class="card"><span class="tag">${esc(r.company||r.category||'Resource')}</span><div class="job-title">${esc(r.title)}</div><p class="muted">${esc(r.description||'Preparation resource')}</p><a class="btn primary" href="${esc(r.driveUrl||'#')}" target="_blank" rel="noopener">View / Download</a></article>`}
function socialCard(name,desc,key,icon){return `<a class="social" href="${esc((C.social||{})[key]||'#')}" target="_blank" rel="noopener"><div style="font-size:26px">${icon}</div><b>${name}</b><span class="muted">${desc}</span></a>`}
function jobs(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>Latest Jobs</h2><p class="muted">Search current opportunities. Always verify details on the official employer page.</p></div></div><input class="search" id="q" placeholder="Search company, job title, category or qualification..."><div class="grid" id="jobgrid" style="margin-top:18px">${data.jobs.map(jobCard).join('')||'<div class="empty" style="grid-column:1/-1">No published jobs yet.</div>'}</div></section>`;$('#q').oninput=e=>{$('#jobgrid').innerHTML=data.jobs.filter(j=>JSON.stringify(j).toLowerCase().includes(e.target.value.toLowerCase())).map(jobCard).join('')||'<div class="empty" style="grid-column:1/-1">No matching jobs.</div>'}}
function youtube(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>CareerAxis Academy on YouTube</h2><p class="muted">Latest job notifications, career guidance and preparation videos.</p></div><a class="btn primary" href="${esc(C.youtubeChannelUrl||C.social?.youtube||'#')}" target="_blank">Subscribe on YouTube</a></div><div class="grid">${data.videos.map(videoCard).join('')||'<div class="empty" style="grid-column:1/-1">Connect your YouTube Channel ID and run a sync from the Admin Dashboard.</div>'}</div></section>`}
function resources(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>Resources</h2><p class="muted">Organized by company, exam and career path. Large files can remain in Google Drive.</p></div></div><div class="grid">${data.resources.map(resourceCard).join('')||'<div class="empty" style="grid-column:1/-1">No resources published yet.</div>'}</div></section>`}
function careers(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>Career Paths</h2><p class="muted">Explore what you can do after school, intermediate and graduation.</p></div></div><div class="grid">${data.careerPaths.map(x=>`<article class="card"><span class="tag">Career Path</span><div class="job-title">${esc(x)}</div><p class="muted">Add detailed guidance, courses, exams, jobs and videos from the Admin Dashboard.</p></article>`).join('')}</div></section>`}
function calendar(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>Job & Exam Calendar</h2><p class="muted">Deadlines, exams and important career dates.</p></div></div><div class="calendar">${data.events.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<article class="card"><span class="tag">${esc(e.type)}</span><div class="job-title">${esc(e.title)}</div><b>${esc(e.date)}</b></article>`).join('')||'<div class="empty" style="grid-column:1/-1">No upcoming events.</div>'}</div></section>`}
function community(){ $('#app').innerHTML=`<section class="section"><div class="section-head"><div><h2>Join the Community</h2><p class="muted">Official links configured by the CareerAxis Academy admin.</p></div></div><div class="socials">${socialCard('YouTube','Subscribe','youtube','▶')}${socialCard('Telegram','Join channel','telegram','✈')}${socialCard('WhatsApp','Join community','whatsapp','◉')}${socialCard('Instagram','Follow','instagram','◎')}</div></section>`}
async function admin(){
  document.title='CareerAxis Academy — Secure Admin';
  const auth=window.CareerAxisAuth;
  if(!auth){ $('#app').innerHTML='<section class="section"><div class="empty">Authentication module unavailable.</div></section>'; return; }
  const state=await auth.initAdminAuth();
  if(!state.configured){
    $('#app').innerHTML=`<section class="section admin-gate"><div class="admin-box"><span class="tag">SECURE ADMIN</span><h2>CareerAxis Academy Control Center</h2><p class="muted">Supabase authentication is not configured yet.</p><p>Complete <b>docs/SUPABASE-SETUP.md</b>, then add the Supabase URL and anon key to <b>site-config.js</b>.</p><a class="btn primary" href="#home">Back to Website</a></div></section>`; return;
  }
  if(!state.user){
    $('#app').innerHTML=`<section class="section admin-gate"><div class="admin-box"><span class="tag">PRIVATE AREA</span><h2>Admin Sign In</h2><p class="muted">This control center is intentionally hidden from the public navigation.</p><button class="btn primary" id="googleAdmin">Continue with Google</button><p class="tiny">Only the two authorized CareerAxis Academy Google accounts can continue.</p></div></section>`;
    $('#googleAdmin').onclick=async()=>{try{await auth.signInWithGoogle()}catch(e){alert(e.message)}};
    return;
  }
  if(!state.authorized){
    $('#app').innerHTML=`<section class="section admin-gate"><div class="admin-box"><span class="tag">ACCESS DENIED</span><h2>Unauthorized account</h2><p class="muted">${esc(state.user.email||'This Google account')} is not one of the two authorized admin accounts.</p><button class="btn" id="logoutAdmin">Sign out</button></div></section>`;
    $('#logoutAdmin').onclick=auth.signOutAdmin; return;
  }
  if(!auth.hasRecentOtpVerification()){
    $('#app').innerHTML=`<section class="section admin-gate"><div class="admin-box"><span class="tag">SECOND FACTOR</span><h2>Verify Admin OTP</h2><p class="muted">Google authentication succeeded for <b>${esc(state.user.email)}</b>.</p><p>A one-time code will be sent to the protected CareerAxis security mailbox.</p><p><b>OTP destination:</b> ${esc(C.otpDestinationLabel||'protected mailbox')}</p><button class="btn primary" id="sendOtp">Send OTP</button><div id="otpForm" style="display:none;margin-top:18px"><input class="search" id="otpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="Enter 6-digit OTP"><button class="btn primary" id="verifyOtp" style="margin-top:10px">Verify OTP</button></div><p id="otpMsg" class="tiny"></p><button class="btn" id="logoutAdmin" style="margin-top:10px">Sign out</button></div></section>`;
    $('#sendOtp').onclick=async()=>{const b=$('#sendOtp');b.disabled=true;try{await auth.requestAdminOtp();$('#otpForm').style.display='block';$('#otpMsg').textContent='OTP sent. It expires quickly and can be used once.'}catch(e){$('#otpMsg').textContent=e.message;b.disabled=false}};
    $('#verifyOtp').onclick=async()=>{const code=$('#otpCode').value.trim();if(!/^\d{6}$/.test(code)){alert('Enter the 6-digit OTP.');return}try{await auth.verifyAdminOtp(code);render()}catch(e){alert(e.message)}};
    $('#logoutAdmin').onclick=auth.signOutAdmin; return;
  }
  $('#app').innerHTML=`<section class="section"><div class="section-head"><div><span class="tag">ADMIN</span><h2>CareerAxis Academy Control Center</h2><p class="muted">Signed in as ${esc(state.user.email)} · OTP verified for this session.</p></div><button class="btn" id="logoutAdmin">Sign out</button></div><div class="grid"><div class="card"><span class="tag">Content</span><div class="job-title">Jobs & Calendar</div><p class="muted">Manage jobs, deadlines and events.</p><button class="btn primary" onclick="demoNotice()">Open manager</button></div><div class="card"><span class="tag">YouTube</span><div class="job-title">Channel Integration</div><p class="muted">Channel ID: ${esc(C.youtubeChannelId||'Not configured')}</p><button class="btn primary" onclick="demoNotice()">Configure sync</button></div><div class="card"><span class="tag">Google Drive</span><div class="job-title">Folder Mapping</div><p class="muted">Drive owner: ${esc(C.driveOwnerAccount||'careeraxisacademy@gmail.com')}</p><button class="btn primary" onclick="demoNotice()">Manage mappings</button></div><div class="card"><span class="tag">Social</span><div class="job-title">Community Links</div><p class="muted">Update YouTube, Telegram, WhatsApp and Instagram links.</p><button class="btn primary" onclick="demoNotice()">Edit social links</button></div><div class="card"><span class="tag">Security</span><div class="job-title">2 Admin Accounts + OTP</div><p class="muted">Authorized: careeraxisacademy@gmail.com and ravitejasiddana@gmail.com. OTP: ${esc(C.otpDestinationLabel||'protected')}</p><button class="btn primary" onclick="demoNotice()">Security settings</button></div><div class="card"><span class="tag">Automation</span><div class="job-title">Sync Center</div><p class="muted">YouTube sync · Drive sync · job expiry · link checks · sitemap.</p><button class="btn primary" onclick="demoNotice()">Run / view logs</button></div></div><div class="card" style="margin-top:18px"><h3>Connected-service rule</h3><p class="muted">The production Google Drive connector must use OAuth for <b>careeraxisacademy@gmail.com</b> only. Do not place Google service-account private keys, refresh tokens, or other secrets in this website's JavaScript.</p></div></section>`;
  $('#logoutAdmin').onclick=auth.signOutAdmin;
}
function demoNotice(){alert('This control is a secure-integration placeholder in the starter package. Complete SUPABASE-SETUP.md and deploy the Edge Functions before enabling production admin actions.')}
$('#menu').onclick=()=>$('#nav').classList.toggle('open');$('#lang').onclick=()=>{lang=lang==='en'?'te':'en';$('#lang').textContent=lang==='en'?'తెలుగు':'English';alert(lang==='te'?'Telugu content can be added per record in the Admin CMS.':'English mode enabled.')};window.addEventListener('hashchange',render);load();
