-- CareerAxis Academy production database starter
-- Run in Supabase SQL Editor after creating a Supabase project.
-- Passwords must be handled by Supabase Auth, NOT by this database schema.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  preferred_language text default 'en' check (preferred_language in ('en','te')),
  role text default 'student' check (role in ('student','instructor','admin')),
  created_at timestamptz default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  title_te text,
  description text,
  description_te text,
  category text,
  level text,
  price numeric(10,2) default 0,
  thumbnail_url text,
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  title text not null,
  title_te text,
  youtube_video_id text,
  lesson_order int not null default 1,
  is_preview boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  course_id bigint references public.courses(id) on delete cascade,
  status text default 'active',
  enrolled_at timestamptz default now(),
  unique(user_id,course_id)
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete cascade,
  completed boolean default false,
  completed_at timestamptz,
  unique(user_id,lesson_id)
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  title_te text,
  description text,
  url text,
  resource_type text,
  published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now()
);

-- Enable Row Level Security before production use.
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.resources enable row level security;
alter table public.contact_messages enable row level security;

-- Production policies should be designed for your exact admin/instructor model.
-- Do not expose contact_messages or private student data publicly.
